### ISSUE TITLE
A few issues in the install

### ISSUE THREAD

**Issue by samjaninf** [openflixr/OpenFLIXR2.SetupScript#10]
Hey, thank you very much for this.

Wanted to point out these from a brand new install:

````
- Lidarr
sed: can't read /home/openflixr/.config/Lidarr/config.xml: No such file or directory
- Lazylibrarian
- Tautulli (PlexPy)
File contains parsing errors: <???>
        [line 415]: [[get_file_sizes_hold]]
````

**Comment by MagicalCodeMonkey** [comment]
Thanks for reporting this! I've been focused on another project over the last couple of weeks but I'll try to circle back to this soon and see if I can figure out what is going on.

**Comment by MagicalCodeMonkey** [comment]
This should fix the error with Tautulli - https://github.com/MagicalCodeMonkey/OpenFLIXR2.SetupScript/pull/11
Will investigate the Lidarr issue more later

**Comment by MagicalCodeMonkey** [comment]
This should now be resolved
