### ISSUE TITLE
a question about openflixr2

### ISSUE THREAD

**Issue by twisted-fire-starter** [openflixr/OpenFLIXR2.SetupScript#41]
hi would there be any chance of a .iso file of this please as its based of ubuntu and i would like to be able to install it directly on to a spare computer i have

**Comment by jeremysherriff** [comment]
No - there's no OS install capabilities. This is a running VM image, there
is no supportable way to transplant onto bare hardware.
You can download one of the image files and attempt a V2P if you want, but
we have no way to assist you on this.
