### ISSUE TITLE
using the script to setup a fresh ubuntu install

### ISSUE THREAD

**Issue by nigifabio** [openflixr/OpenFLIXR2.SetupScript#71]
Hello,
first of all: great work! I'm playing with the image but I would like to setup directly on the bare hw without a hypervisor, is the script working if I use it on a fresh ubuntu install?

**Comment by MagicalCodeMonkey** [comment]
Unfortunately, no. The script requires the image to run.

**Comment by mvthul** [comment]
Just clone with acronis or macrium (create image rollout and test)

Op 27 sep. 2019 om 11:39 heeft Fabio Nigi <notifications@github.com> het volgende geschreven:

﻿

Hello,
first of all: great work! I'm playing with the image but I would like to setup directly on the bare hw without a hypervisor, is the script working if I use it on a fresh ubuntu install?
